#!/bin/bash

#全局配置
php_version="php-7.1.7"
nginx_version="nginx-1.13.3"
mysql_version="mysql-5.7.18"
boost_version="boost_1_59_0"

php_dir=${php_version}".tar.gz"
nginx_dir=${nginx_version}".tar.gz"
mysql_dir=${mysql_version}".tar.gz"
boost_dir=${boost_version}".tar.gz"

data_path="/home"
www_path=${data_path}"/data"
mysql_data_path=${data_path}"/mysql"

cpu_cores=$(grep 'cpu cores' /proc/cpuinfo |uniq |awk -F : '{print $2}' |sed 's/^[ \t]*//g')



mkdir -p ${www_path}
mkdir -p ${mysql_data_path}

groupadd www
useradd -r -g www www

groupadd mysql
useradd -r -g mysql mysql

#安装必要的安装包
yum install wget -y
mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.backup
wget -O /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-6.repo

yum install epel-release -y

yum update -y

yum -y install gcc make cmake gcc-c++ libxml2 libxml2-python libxml2-devel libmcrypt libmcrypt-devel libmcrypt php-mcrypt mhash pcre* openssl* gd-devel* zlib-devel pcre-devel  curl-devel ncurses-devel perl expat-devel

if [ ! -f "$php_dir" ]; then
	echo "找不到php安装包，请确认安装包是否完整"
elif [ ! -f "$mysql_dir" ]; then
	echo "找不到mysql安装包，请确认安装包是否完整"
elif [ ! -f "$nginx_dir" ]; then
	echo "找不到nginx安装包，请确认安装包是否完整"
fi

echo "正在解压nginx..."
tar -xf $nginx_dir
if [! -d "$nginx_version" ]; then
	echo "nginx安装包解压失败"
fi
echo "解压nginx安装包完成，正在安装..."

cd $nginx_version

./configure --user=www --group=www --prefix=/usr/local/nginx/ --with-http_v2_module --with-http_ssl_module --with-http_sub_module --with-http_stub_status_module --with-http_gzip_static_module --with-pcre

make && make install

echo "安装nginx完成"

cd ../

echo "正在解压php..."
tar -xf $php_dir
if [ ! -d "$php_version" ]; then
        echo "php安装包解压失败"
fi
echo "解压php安装包完成，正在安装..."

cd $php_version
./configure --prefix=/usr/local/php --with-config-file-path=/etc --enable-fpm --enable-pcntl --enable-mysqlnd --enable-opcache --enable-sockets --enable-sysvmsg --enable-sysvsem  --enable-sysvshm --enable-shmop --enable-zip --enable-ftp --enable-soap --enable-xml --enable-mbstring --disable-rpath --disable-debug --disable-fileinfo --with-mysql=mysqlnd --with-mysqli --with-pdo-mysql --with-pcre-regex --with-iconv --with-zlib --with-mcrypt --with-gd --with-openssl --with-mhash --with-xmlrpc --with-curl --with-imap-ssl --with-jpeg-dir --with-png-dir --with-freetype-dir --enable-fileinfo--enable-inline-optimization --enable-zend-multibyte
make && make install

echo "安装php完成"
cd ../
echo "正在解压mysql..."
tar -xf $mysql_dir
if [ ! -d "$mysql_version" ]; then
        echo "mysql安装包解压失败"
fi
echo "解压mysql安装包完成，正在安装..."
tar -xf $boost_dir
if [ ! -d "$boost_version" ]; then
	echo "boost tar error"
fi
mv $boost_version /usr/local/boost
cd $mysql_version
cmake -DCMAKE_INSTALL_PREFIX=/usr/local/mysql -DMYSQL_DATADIR=${mysql_data_path} -DMYSQL_UNIX_ADDR=/tmp/mysql.sock -DDEFAULT_CHARSET=utf8 -DDEFAULT_COLLATION=utf8_general_ci -DEXTRA_CHARSETS=all -DENABLED_LOCAL_INFILE=1 -DWITH_BOOST=/usr/local/boost
if [ $cpu_cores = "1" ]; then
	make && make install
else
	make -j $cpu_cores && make install
fi

mv /etc/my.cnf /etc/my.cnf.lzd
cp conf/my.cnf /etc/my.cnf

/usr/local/mysql/bin/mysqld --initialize --user=mysql --datadir=${mysql_data_path} --basedir=/usr/local/mysql --socket=/tmp/mysql.sock

echo "安装mysql完成"
cd ../
echo "读写配置中，请稍后"

mv /etc/php.ini /etc/php.ini.lzd
cp conf/php.ini /etc/php.ini
cp bin/mysqld /etc/init.d/mysqld


echo "<?php phpinfo();" >> ${www_path}/index.php
echo "PATH=$PATH:/usr/local/php/bin:/usr/local/mysql/bin" >> /etc/profile
echo "export PATH" >> /etc/profile

echo "读写配置完成"

rm -rf $php_version
rm -rf $nginx_version
rm -rf $mysql_version
rm -rf $boost_version

#变更用户组
chown -R www:www /usr/local/nginx
chown -R www:www /usr/local/php
chown -R www:www /usr/local/mysql
chown -R www:www ${mysql_data_path}
