#!/bin/bash

#全局配置
php_version="php-7.1.7"
apache_version="httpd-2.4.27"
apr_version="apr-1.6.2"
apr_util_version="apr-util-1.6.0"
nginx_version="nginx-1.13.3"
mysql_version="mysql-5.7.18"
boost_version="boost_1_59_0"

php_dir=${php_version}".tar.gz"
apache_dir=${apache_version}".tar.gz"
apr_dir=${apr_version}".tar.gz"
apr_util_dir=${apr_util_version}".tar.gz"
nginx_dir=${nginx_version}".tar.gz"
mysql_dir=${mysql_version}".tar.gz"
boost_dir=${boost_version}".tar.gz"

cpu_cores=$(grep 'cpu cores' /proc/cpuinfo |uniq |awk -F : '{print $2}' |sed 's/^[ \t]*//g')

mkdir -p /data/www;
mkdir -p /data/mysql;

groupadd mysql;
useradd -r -g mysql mysql

#安装必要的安装包
yum install wget -y
mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.backup;
wget -O /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-6.repo

yum install epel-release -y

yum update -y

yum -y install gcc make cmake gcc-c++ libxml2 libxml2-python libxml2-devel libmcrypt libmcrypt-devel libmcrypt php-mcrypt mhash pcre* openssl* gd-devel* zlib-devel pcre-devel  curl-devel ncurses-devel perl expat-devel

if [ ! -f "$php_dir" ]; then
	echo "找不到php安装包，请确认安装包是否完整"
elif [ ! -f "$apache_dir" ]; then
	echo "找不到apache安装包，请确认安装包是否完整"
elif [ ! -f "$apr_dir" ]; then
	echo "找不到apr安装包，请确认安装包是否完整"
elif [ ! -f "$apr_util_dir" ]; then
	echo "找不到apr-util安装包，请确认安装包是否完整"
elif [ ! -f "$mysql_dir" ]; then
	echo "找不到mysql安装包，请确认安装包是否完整"
fi

echo "正在解压apr..."
tar -xf $apr_dir
if [ ! -d "$apr_version" ]; then
	echo "apr安装包解压失败"
fi
echo "解压apr安装包完成，正在安装..."
cd $apr_version;
./configure --prefix=/usr/local/apr;
make && make install;
echo "安装apr完成"
cd ../;
echo "正在解压apr_util..."
tar -xf $apr_util_dir
if [ ! -d "$apr_util_version" ]; then
        echo "apr-util安装包解压失败"
fi
echo "解压apr-util安装包完成，正在安装..."
cd $apr_util_version;
./configure --prefix=/usr/local/apr-util --with-apr=/usr/local/apr;
make && make install;
echo "安装apr-util完成"
cd ../;
echo "正在解压apache..."
tar -xf $apache_dir
if [ ! -d "$apache_version" ]; then
        echo "apache安装包解压失败"
fi
echo "解压apache安装包完成，正在安装..."
cd $apache_version;
./configure --prefix=/usr/local/apache --with-apr=/usr/local/apr --with-apr-util=/usr/local/apr-util --enable-so --enable-ssl --enable-cgi --enable-rewrite --with-zlib --with-pcre --enable-modules=all --enable-mpms-shared=all --with-mpm=prefork;
make && make install;
echo "安装apache完成"
cd ../;
echo "正在解压php..."
tar -xf $php_dir
if [ ! -d "$php_version" ]; then
        echo "php安装包解压失败"
fi
echo "解压php安装包完成，正在安装..."
cd $php_version;
./configure --prefix=/usr/local/php --with-config-file-path=/etc --enable-fpm --enable-pcntl --enable-mysqlnd --enable-opcache --enable-sockets --enable-sysvmsg --enable-sysvsem  --enable-sysvshm --enable-shmop --enable-zip --enable-ftp --enable-soap --enable-xml --enable-mbstring --disable-rpath --disable-debug --disable-fileinfo --with-mysql=mysqlnd --with-mysqli --with-pdo-mysql --with-pcre-regex --with-iconv --with-zlib --with-mcrypt --with-gd --with-openssl --with-mhash --with-xmlrpc --with-curl --with-imap-ssl --with-jpeg-dir --with-png-dir --with-freetype-dir --enable-fileinfo--enable-inline-optimization --enable-zend-multibyte --with-apxs2=/usr/local/apache/bin/apxs;
make && make install;
echo "安装php完成"
cd ../;
echo "正在解压mysql..."
tar -xf $mysql_dir
if [ ! -d "$mysql_version" ]; then
        echo "mysql安装包解压失败"
fi
echo "解压mysql安装包完成，正在安装..."
tar -xf $boost_dir
if [ ! -d "$boost_version" ]; then
	echo "boost tar error"
fi
mv $boost_version /usr/local/boost;
cd $mysql_version
cmake -DCMAKE_INSTALL_PREFIX=/usr/local/mysql -DMYSQL_DATADIR=/data/mysql -DMYSQL_UNIX_ADDR=/tmp/mysql.sock -DDEFAULT_CHARSET=utf8 -DDEFAULT_COLLATION=utf8_general_ci -DEXTRA_CHARSETS=all -DENABLED_LOCAL_INFILE=1 -DWITH_BOOST=/usr/local/boost
if [ $cpu_cores = "1" ]; then
	make && make install;
else
	make -j $cpu_cores && make install;
fi

/usr/local/mysql/bin/mysqld --initialize --user=mysql --datadir=/data/mysql --basedir=/usr/local/mysql --socket=/tmp/mysql.sock

echo "安装mysql完成"
cd ../
echo "读写配置中，请稍后"
mv /usr/local/apache/conf/httpd.conf /usr/local/apache/conf/httpd.conf.lzd;
mv /usr/local/apache/conf/extra/httpd-vhosts.conf /usr/local/apache/conf/extra/httpd-vhosts.conf.lzd;
mv /etc/my.cnf /etc/my.cnf.lzd;
mv /etc/php.ini /etc/php.ini.lzd;
cp conf/httpd.conf /usr/local/apache/conf/httpd.conf;
cp conf/httpd-vhosts.conf /usr/local/apache/conf/extra/httpd-vhosts.conf;
cp conf/php.ini /etc/php.ini;
cp conf/my.cnf /etc/my.cnf;
cp bin/mysqld /etc/init.d/mysqld;
cp bin/httpd /etc/init.d/httpd;


echo "<?php phpinfo();" >> /data/www/index.php;
echo "PATH=$PATH:/usr/local/php/bin:/usr/local/mysql/bin" >> /etc/profile;
echo "export PATH" >> /etc/profile;

echo "读写配置完成"

